//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lbk.MobileApp.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lbk.MobileApp.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AnswerDescriptionLabelText {
            get {
                return ResourceManager.GetString("AnswerDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string AnswerDescriptionRequired {
            get {
                return ResourceManager.GetString("AnswerDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string AnswerDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("AnswerDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string AnswerExplanationLabelText {
            get {
                return ResourceManager.GetString("AnswerExplanationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation is required..
        /// </summary>
        public static string AnswerExplanationRequired {
            get {
                return ResourceManager.GetString("AnswerExplanationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation must be less than 255 characters..
        /// </summary>
        public static string AnswerExplanationStringLengthValidationError {
            get {
                return ResourceManager.GetString("AnswerExplanationStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is right.
        /// </summary>
        public static string AnswerIsRightLabelText {
            get {
                return ResourceManager.GetString("AnswerIsRightLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CategoryDescriptionLabelText {
            get {
                return ResourceManager.GetString("CategoryDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string CategoryDescriptionRequired {
            get {
                return ResourceManager.GetString("CategoryDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string CategoryDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("CategoryDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CategoryTitleLabelText {
            get {
                return ResourceManager.GetString("CategoryTitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string CategoryTitleRequired {
            get {
                return ResourceManager.GetString("CategoryTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be less than 255 characters..
        /// </summary>
        public static string CategoryTitleStringLengthValidationError {
            get {
                return ResourceManager.GetString("CategoryTitleStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated at.
        /// </summary>
        public static string EventActivatedAtLabelText {
            get {
                return ResourceManager.GetString("EventActivatedAtLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated at is required..
        /// </summary>
        public static string EventActivatedAtRequired {
            get {
                return ResourceManager.GetString("EventActivatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activated at date must be between 1900 and 2100..
        /// </summary>
        public static string EventActivatedAtYearRangeValidationError {
            get {
                return ResourceManager.GetString("EventActivatedAtYearRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string EventDateLabelText {
            get {
                return ResourceManager.GetString("EventDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date order.
        /// </summary>
        public static string EventDateOrderLabelText {
            get {
                return ResourceManager.GetString("EventDateOrderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date order is required..
        /// </summary>
        public static string EventDateOrderRequired {
            get {
                return ResourceManager.GetString("EventDateOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date order date must be between 1900 and 2100..
        /// </summary>
        public static string EventDateOrderYearRangeValidationError {
            get {
                return ResourceManager.GetString("EventDateOrderYearRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required..
        /// </summary>
        public static string EventDateRequired {
            get {
                return ResourceManager.GetString("EventDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be less than 255 characters..
        /// </summary>
        public static string EventDateStringLengthValidationError {
            get {
                return ResourceManager.GetString("EventDateStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EventDescriptionLabelText {
            get {
                return ResourceManager.GetString("EventDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string EventDescriptionRequired {
            get {
                return ResourceManager.GetString("EventDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string EventDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("EventDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at.
        /// </summary>
        public static string EventExpiresAtLabelText {
            get {
                return ResourceManager.GetString("EventExpiresAtLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at is required..
        /// </summary>
        public static string EventExpiresAtRequired {
            get {
                return ResourceManager.GetString("EventExpiresAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expires at date must be between 1900 and 2100..
        /// </summary>
        public static string EventExpiresAtYearRangeValidationError {
            get {
                return ResourceManager.GetString("EventExpiresAtYearRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is activated.
        /// </summary>
        public static string EventIsActivatedLabelText {
            get {
                return ResourceManager.GetString("EventIsActivatedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservationlink.
        /// </summary>
        public static string EventReservationLinkLabelText {
            get {
                return ResourceManager.GetString("EventReservationLinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservationlink must be less than 255 characters..
        /// </summary>
        public static string EventReservationLinkStringLengthValidationError {
            get {
                return ResourceManager.GetString("EventReservationLinkStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnaillink.
        /// </summary>
        public static string EventThumbnailLinkLabelText {
            get {
                return ResourceManager.GetString("EventThumbnailLinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnaillink must be less than 255 characters..
        /// </summary>
        public static string EventThumbnailLinkStringLengthValidationError {
            get {
                return ResourceManager.GetString("EventThumbnailLinkStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EventTitleLabelText {
            get {
                return ResourceManager.GetString("EventTitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string EventTitleRequired {
            get {
                return ResourceManager.GetString("EventTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be less than 255 characters..
        /// </summary>
        public static string EventTitleStringLengthValidationError {
            get {
                return ResourceManager.GetString("EventTitleStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string FoodCategoryIdLabelText {
            get {
                return ResourceManager.GetString("FoodCategoryIdLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string FoodCategoryNameLabelText {
            get {
                return ResourceManager.GetString("FoodCategoryNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FoodDescriptionLabelText {
            get {
                return ResourceManager.GetString("FoodDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string FoodDescriptionRequired {
            get {
                return ResourceManager.GetString("FoodDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string FoodDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("FoodDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string FoodPriceLabelText {
            get {
                return ResourceManager.GetString("FoodPriceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Price must be between 0 and 1000..
        /// </summary>
        public static string FoodPriceRangeValidationError {
            get {
                return ResourceManager.GetString("FoodPriceRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required..
        /// </summary>
        public static string FoodPriceRequired {
            get {
                return ResourceManager.GetString("FoodPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortorder.
        /// </summary>
        public static string FoodSortOrderLabelText {
            get {
                return ResourceManager.GetString("FoodSortOrderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sortorder must be between 1 and 10000..
        /// </summary>
        public static string FoodSortOrderRangeValidationError {
            get {
                return ResourceManager.GetString("FoodSortOrderRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortorder is required..
        /// </summary>
        public static string FoodSortOrderRequired {
            get {
                return ResourceManager.GetString("FoodSortOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FoodTitleLabelText {
            get {
                return ResourceManager.GetString("FoodTitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be less than 255 characters..
        /// </summary>
        public static string FoodTitleStringLengthValidationError {
            get {
                return ResourceManager.GetString("FoodTitleStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha-numeric characters and [.,_-:\/?&apos;] are allowed..
        /// </summary>
        public static string InvalidInputCharacter {
            get {
                return ResourceManager.GetString("InvalidInputCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha-numeric characters, new lines, and [.,_-:\/?&apos;] are allowed..
        /// </summary>
        public static string InvalidMultilineInput {
            get {
                return ResourceManager.GetString("InvalidMultilineInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MenuDateLabelText {
            get {
                return ResourceManager.GetString("MenuDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date at is required..
        /// </summary>
        public static string MenuDateRequired {
            get {
                return ResourceManager.GetString("MenuDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be between 1900 and 2100..
        /// </summary>
        public static string MenuDateYearRangeValidationError {
            get {
                return ResourceManager.GetString("MenuDateYearRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MenuDescriptionLabelText {
            get {
                return ResourceManager.GetString("MenuDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string MenuDescriptionRequired {
            get {
                return ResourceManager.GetString("MenuDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string MenuDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("MenuDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PictureDescriptionLabelText {
            get {
                return ResourceManager.GetString("PictureDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string PictureDescriptionRequired {
            get {
                return ResourceManager.GetString("PictureDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string PictureDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("PictureDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        public static string PictureFileNameLabelText {
            get {
                return ResourceManager.GetString("PictureFileNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName is required..
        /// </summary>
        public static string PictureFileNameRequired {
            get {
                return ResourceManager.GetString("PictureFileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName must be less than 255 characters..
        /// </summary>
        public static string PictureFileNameStringLengthValidationError {
            get {
                return ResourceManager.GetString("PictureFileNameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string PictureLinkLabelText {
            get {
                return ResourceManager.GetString("PictureLinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is required..
        /// </summary>
        public static string PictureLinkRequired {
            get {
                return ResourceManager.GetString("PictureLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link must be less than 255 characters..
        /// </summary>
        public static string PictureLinkStringLengthValidationError {
            get {
                return ResourceManager.GetString("PictureLinkStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortorder.
        /// </summary>
        public static string PictureSortOrderLabelText {
            get {
                return ResourceManager.GetString("PictureSortOrderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sortorder must be between 1 and 10000..
        /// </summary>
        public static string PictureSortOrderRangeValidationError {
            get {
                return ResourceManager.GetString("PictureSortOrderRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortorder is required..
        /// </summary>
        public static string PictureSortOrderRequired {
            get {
                return ResourceManager.GetString("PictureSortOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string QuestionDescriptionLabelText {
            get {
                return ResourceManager.GetString("QuestionDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string QuestionDescriptionRequired {
            get {
                return ResourceManager.GetString("QuestionDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string QuestionDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("QuestionDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string QuestionNumberLabelText {
            get {
                return ResourceManager.GetString("QuestionNumberLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be between 1 and 255..
        /// </summary>
        public static string QuestionNumberRangeValidationError {
            get {
                return ResourceManager.GetString("QuestionNumberRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is required..
        /// </summary>
        public static string QuestionNumberRequired {
            get {
                return ResourceManager.GetString("QuestionNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string QuestionPointsLabelText {
            get {
                return ResourceManager.GetString("QuestionPointsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The points must be between 1 and 255..
        /// </summary>
        public static string QuestionPointsRangeValidationError {
            get {
                return ResourceManager.GetString("QuestionPointsRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points is required..
        /// </summary>
        public static string QuestionPointsRequired {
            get {
                return ResourceManager.GetString("QuestionPointsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated at.
        /// </summary>
        public static string SerieActivatedAtLabelText {
            get {
                return ResourceManager.GetString("SerieActivatedAtLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated at is required..
        /// </summary>
        public static string SerieActivatedAtRequired {
            get {
                return ResourceManager.GetString("SerieActivatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activated at date must be between 1900 and 2100..
        /// </summary>
        public static string SerieActivatedAtYearRangeValidationError {
            get {
                return ResourceManager.GetString("SerieActivatedAtYearRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SerieDescriptionLabelText {
            get {
                return ResourceManager.GetString("SerieDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string SerieDescriptionRequired {
            get {
                return ResourceManager.GetString("SerieDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string SerieDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("SerieDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at.
        /// </summary>
        public static string SerieExpiresAtLabelText {
            get {
                return ResourceManager.GetString("SerieExpiresAtLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at is required..
        /// </summary>
        public static string SerieExpiresAtRequired {
            get {
                return ResourceManager.GetString("SerieExpiresAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expires at date must be between 1900 and 2100..
        /// </summary>
        public static string SerieExpiresAtYearRangeValidationError {
            get {
                return ResourceManager.GetString("SerieExpiresAtYearRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is activated.
        /// </summary>
        public static string SerieIsActivatedLabelText {
            get {
                return ResourceManager.GetString("SerieIsActivatedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!.*--)[\w\.,&apos;_ \-:\\\/?=]*$.
        /// </summary>
        public static string TextLineInputValidatorRegEx {
            get {
                return ResourceManager.GetString("TextLineInputValidatorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!.*--)[A-Za-z0-9\.,&apos;_ \-:\\\/?=]*$.
        /// </summary>
        public static string TextLineInputValidatorRegExUnicode {
            get {
                return ResourceManager.GetString("TextLineInputValidatorRegExUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!.*--)([\w\.,&apos;_ \-:\\\/?=]|\r|\n)*$.
        /// </summary>
        public static string TextMultilineValidatorRegEx {
            get {
                return ResourceManager.GetString("TextMultilineValidatorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!.*--)([A-Za-z0-9\.,&apos;_ \-:\\\/?=]|\r|\n)*$.
        /// </summary>
        public static string TextMultilineValidatorRegExUnicode {
            get {
                return ResourceManager.GetString("TextMultilineValidatorRegExUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add answer..
        /// </summary>
        public static string UnableToAddAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add category..
        /// </summary>
        public static string UnableToAddCategoryExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddCategoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add event..
        /// </summary>
        public static string UnableToAddEventExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddEventExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add food..
        /// </summary>
        public static string UnableToAddFoodExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddFoodExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add menu..
        /// </summary>
        public static string UnableToAddMenuExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddMenuExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add picture..
        /// </summary>
        public static string UnableToAddPictureExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddPictureExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add question..
        /// </summary>
        public static string UnableToAddQuestionExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddQuestionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add serie..
        /// </summary>
        public static string UnableToAddSerieExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddSerieExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add video..
        /// </summary>
        public static string UnableToAddVideoExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddVideoExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy menu..
        /// </summary>
        public static string UnableToCopyMenuExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCopyMenuExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete answer..
        /// </summary>
        public static string UnableToDeleteAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete category..
        /// </summary>
        public static string UnableToDeleteCategoryExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteCategoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete event..
        /// </summary>
        public static string UnableToDeleteEventExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteEventExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete food..
        /// </summary>
        public static string UnableToDeleteFoodExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteFoodExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete menu..
        /// </summary>
        public static string UnableToDeleteMenuExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteMenuExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete picture..
        /// </summary>
        public static string UnableToDeletePictureExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeletePictureExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete question..
        /// </summary>
        public static string UnableToDeleteQuestionExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteQuestionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete serie..
        /// </summary>
        public static string UnableToDeleteSerieExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteSerieExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete video..
        /// </summary>
        public static string UnableToDeleteVideoExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteVideoExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve answer..
        /// </summary>
        public static string UnableToRetrieveAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve category..
        /// </summary>
        public static string UnableToRetrieveCategoryExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveCategoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve event..
        /// </summary>
        public static string UnableToRetrieveEventExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveEventExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve food..
        /// </summary>
        public static string UnableToRetrieveFoodExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveFoodExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve menu..
        /// </summary>
        public static string UnableToRetrieveMenuExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveMenuExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve picture..
        /// </summary>
        public static string UnableToRetrievePictureExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrievePictureExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve question..
        /// </summary>
        public static string UnableToRetrieveQuestionExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveQuestionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve serie..
        /// </summary>
        public static string UnableToRetrieveSerieExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveSerieExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve video..
        /// </summary>
        public static string UnableToRetrieveVideoExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveVideoExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update answer..
        /// </summary>
        public static string UnableToUpdateAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update category..
        /// </summary>
        public static string UnableToUpdateCategoryExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateCategoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update event..
        /// </summary>
        public static string UnableToUpdateEventExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateEventExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update food..
        /// </summary>
        public static string UnableToUpdateFoodExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateFoodExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update menu..
        /// </summary>
        public static string UnableToUpdateMenuExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateMenuExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update picture..
        /// </summary>
        public static string UnableToUpdatePictureExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdatePictureExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update question..
        /// </summary>
        public static string UnableToUpdateQuestionExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateQuestionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update serie..
        /// </summary>
        public static string UnableToUpdateSerieExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateSerieExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update video..
        /// </summary>
        public static string UnableToUpdateVideoExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateVideoExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string VideoDescriptionLabelText {
            get {
                return ResourceManager.GetString("VideoDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string VideoDescriptionRequired {
            get {
                return ResourceManager.GetString("VideoDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string VideoDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("VideoDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        public static string VideoFileNameLabelText {
            get {
                return ResourceManager.GetString("VideoFileNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName is required..
        /// </summary>
        public static string VideoFileNameRequired {
            get {
                return ResourceManager.GetString("VideoFileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName must be less than 255 characters..
        /// </summary>
        public static string VideoFileNameStringLengthValidationError {
            get {
                return ResourceManager.GetString("VideoFileNameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string VideoLinkLabelText {
            get {
                return ResourceManager.GetString("VideoLinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is required..
        /// </summary>
        public static string VideoLinkRequired {
            get {
                return ResourceManager.GetString("VideoLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link must be less than 255 characters..
        /// </summary>
        public static string VideoLinkStringLengthValidationError {
            get {
                return ResourceManager.GetString("VideoLinkStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortorder.
        /// </summary>
        public static string VideoSortOrderLabelText {
            get {
                return ResourceManager.GetString("VideoSortOrderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sortorder must be between 1 and 10000..
        /// </summary>
        public static string VideoSortOrderRangeValidationError {
            get {
                return ResourceManager.GetString("VideoSortOrderRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortorder is required..
        /// </summary>
        public static string VideoSortOrderRequired {
            get {
                return ResourceManager.GetString("VideoSortOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnaillink.
        /// </summary>
        public static string VideoThumbnailLinkLabelText {
            get {
                return ResourceManager.GetString("VideoThumbnailLinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnaillink must be less than 255 characters..
        /// </summary>
        public static string VideoThumbnailLinkStringLengthValidationError {
            get {
                return ResourceManager.GetString("VideoThumbnailLinkStringLengthValidationError", resourceCulture);
            }
        }
    }
}
