//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lbk.MobileApp.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lbk.MobileApp.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AnswerDescriptionLabelText {
            get {
                return ResourceManager.GetString("AnswerDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string AnswerDescriptionRequired {
            get {
                return ResourceManager.GetString("AnswerDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string AnswerDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("AnswerDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string AnswerExplanationLabelText {
            get {
                return ResourceManager.GetString("AnswerExplanationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation is required..
        /// </summary>
        public static string AnswerExplanationRequired {
            get {
                return ResourceManager.GetString("AnswerExplanationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation must be less than 255 characters..
        /// </summary>
        public static string AnswerExplanationStringLengthValidationError {
            get {
                return ResourceManager.GetString("AnswerExplanationStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is right.
        /// </summary>
        public static string AnswerIsRightLabelText {
            get {
                return ResourceManager.GetString("AnswerIsRightLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha-numeric characters and [.,_-&apos;] are allowed..
        /// </summary>
        public static string InvalidInputCharacter {
            get {
                return ResourceManager.GetString("InvalidInputCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string QuestionDescriptionLabelText {
            get {
                return ResourceManager.GetString("QuestionDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string QuestionDescriptionRequired {
            get {
                return ResourceManager.GetString("QuestionDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string QuestionDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("QuestionDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be between 1 and 255..
        /// </summary>
        public static string QuestionNumberIntRangeValidationError {
            get {
                return ResourceManager.GetString("QuestionNumberIntRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string QuestionNumberLabelText {
            get {
                return ResourceManager.GetString("QuestionNumberLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is required..
        /// </summary>
        public static string QuestionNumberRequired {
            get {
                return ResourceManager.GetString("QuestionNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The points must be between 1 and 255..
        /// </summary>
        public static string QuestionPointsIntRangeValidationError {
            get {
                return ResourceManager.GetString("QuestionPointsIntRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string QuestionPointsLabelText {
            get {
                return ResourceManager.GetString("QuestionPointsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points is required..
        /// </summary>
        public static string QuestionPointsRequired {
            get {
                return ResourceManager.GetString("QuestionPointsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated at.
        /// </summary>
        public static string SerieActivatedAtLabelText {
            get {
                return ResourceManager.GetString("SerieActivatedAtLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated at is required..
        /// </summary>
        public static string SerieActivatedAtRequired {
            get {
                return ResourceManager.GetString("SerieActivatedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activated at date must be between 1900 and 2100..
        /// </summary>
        public static string SerieActivatedAtYearRangeValidationError {
            get {
                return ResourceManager.GetString("SerieActivatedAtYearRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SerieDescriptionLabelText {
            get {
                return ResourceManager.GetString("SerieDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string SerieDescriptionRequired {
            get {
                return ResourceManager.GetString("SerieDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 255 characters..
        /// </summary>
        public static string SerieDescriptionStringLengthValidationError {
            get {
                return ResourceManager.GetString("SerieDescriptionStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at.
        /// </summary>
        public static string SerieExpiresAtLabelText {
            get {
                return ResourceManager.GetString("SerieExpiresAtLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at is required..
        /// </summary>
        public static string SerieExpiresAtRequired {
            get {
                return ResourceManager.GetString("SerieExpiresAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expires at date must be between 1900 and 2100..
        /// </summary>
        public static string SerieExpiresAtYearRangeValidationError {
            get {
                return ResourceManager.GetString("SerieExpiresAtYearRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is activated.
        /// </summary>
        public static string SerieIsActivatedLabelText {
            get {
                return ResourceManager.GetString("SerieIsActivatedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!.*--)[\w\.,&apos;_ \-]*$.
        /// </summary>
        public static string TextLineInputValidatorRegEx {
            get {
                return ResourceManager.GetString("TextLineInputValidatorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!.*--)[A-Za-z0-9\.,&apos;_ \-]*$.
        /// </summary>
        public static string TextLineInputValidatorRegExUnicode {
            get {
                return ResourceManager.GetString("TextLineInputValidatorRegExUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add answer..
        /// </summary>
        public static string UnableToAddAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add question..
        /// </summary>
        public static string UnableToAddQuestionExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddQuestionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add serie..
        /// </summary>
        public static string UnableToAddSerieExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddSerieExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete answer..
        /// </summary>
        public static string UnableToDeleteAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete question..
        /// </summary>
        public static string UnableToDeleteQuestionExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteQuestionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete serie..
        /// </summary>
        public static string UnableToDeleteSerieExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteSerieExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve answer..
        /// </summary>
        public static string UnableToRetrieveAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve question..
        /// </summary>
        public static string UnableToRetrieveQuestionExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveQuestionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve serie..
        /// </summary>
        public static string UnableToRetrieveSerieExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveSerieExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update answer..
        /// </summary>
        public static string UnableToUpdateAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update question..
        /// </summary>
        public static string UnableToUpdateQuestionExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateQuestionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update serie..
        /// </summary>
        public static string UnableToUpdateSerieExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateSerieExceptionMessage", resourceCulture);
            }
        }
    }
}
